version: '3'

services:

  laravel:
    image: josenaldo/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    image: josenaldo/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"
networks:
  laranet:
    driver: bridge
